TASK: Add new Setting to target the right Tracker in Tracking Code
Flowpack/neos-matomo pull request #43
Opened 2022-05-27 13:15 UTC by l-mbert

This adds a new Setting called `system` which is used to target the right Endpoints in the Matomo / Piwik Instance.

The problem is that Matomo uses "new" Endpoints which are `matomo.php` and `matomo.js` in the Tracking Code while Piwik uses `piwik.php` and `piwik.js`. Thus the Package won't work when using a new Matomo Instance.

Excerpt from the "Tracking Code"-Page in Matomo.
![Matomo_System_TrackingCode](https://user-images.githubusercontent.com/43070365/170706401-73742136-76bd-4a80-8eb0-3753d0193437.png)

2022-06-02 07:55 UTC, Sebobo requested changes
Thx, looks good! 
But can you revert the formatting changes?

2022-06-02 07:58 UTC, Sebobo commented
Probably nobody noticed because all Matomo systems I know still had the old name in their default setting.

2022-06-02 12:53 UTC, l-mbert commented
> Thx, looks good! But can you revert the formatting changes?

Whoops, sorry, didn't even notice that. Should be reverted!

Yeah, we just noticed because we setup a completely new System for ourselves.

2022-11-07 09:37 UTC, kdambekalns commented on Readme.md
> +          system: 'matomo' # Optional
```suggestion
          system: 'matomo' # Optional, "matomo" or "piwik"
```

2022-11-07 09:37 UTC, kdambekalns commented on Readme.md
> +You can change the System you're using so it will target the right Tracking Code.
```suggestion
You can change the System you're using so it will target the right Tracking Code.
Defaults to `matomo`, if needed, set it to `piwik`
```

2022-11-07 09:38 UTC, kdambekalns approved these changes
By reading…

2022-11-08 10:35 UTC, Sebobo approved these changes

2022-11-08 10:36 UTC, merged